version: '3'

services:
  nginx:
    image: $DOCKER_ID/$GITEA_IMAGE
    build:
      context: ./gitea
      args:
        IMAGE_TAG: $DOCKER_ID/$BASE_IMAGE
        IMAGE_VERSION: $ALPINE_VERSION
    restart: unless-stopped
    ports:
      - "22:22"
      - "3000:3000"
